import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Carollie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=pencerio@50&display=swap" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
