import type { Metadata } from "next";
import "./../../app/globals.css";
import Header from "../pages/common/Header";
import Footer from "../pages/common/Footer";

export const metadata: Metadata = {
  title: "Carollie - Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
